### ISSUE TITLE
Unexpected token 0.0.7-beta12

### ISSUE THREAD

**Issue by mordra** [gadicc/meteor-react-hotloader#10]
I'm running the latest version:
```
gadicc:babel-compiler-hot@0.0.6-beta.12
gadicc:ecmascript-hot@0.0.7-beta.12
gadicc:hot@0.0.7
gadicc:modules-runtime-hot@0.0.3-beta.12
```

But it gives me this error on build:
```
> Errors prevented startup:                  
   
   While processing files with gadicc:ecmascript-hot (for target web.browser):
   client/charCreation/attributes.jsx:58:14: Unexpected token (58:14)
   
=> Your application has errors. Waiting for file change.
```

```javascript
//attributes.jsx
const getAttributeDescription = (name, value) => {
  return (_.find(AttributeDescriptions[name], function (desc) {
      return value <= desc.value;
  }) || {}).text || '';  //<--------- ln: 58
};
```

When I remove the function it works fine. Looks like there might be some regex issues with resolving what's a component?

I'm also open to writing better components if that helps.

**Comment by gadicc** [comment]
Ah, damn, this what I meant when I said I was worried about false positives :(  It sees the `return (` and because it's a jsx file that imports React, it incorrectly assumes this is a react stateless component.  For a quick fix, just insert some non whitespace there (temporarily) so the regex won't match, like a meaningless comment i.e:

```js
return (_.find(AttributeDescriptions[name], function (desc) {
return /* */ (_.find(AttributeDescriptions[name], function (desc) {
```

I'll have to think about this more.  Maybe unless it's a `return ( <` (i.e. the start of some jsx) we can require the user to manually opt in with a comment.  Did you come across any other situations like this?

**Comment by mordra** [comment]
I can put in a comment to break the regex.

Once commented out, it builds so no other scenarios.

I was also about to suggest matching for jsx elements in the function since most stateless react functions would be presentation components.
Instead of `return (<`, I'd match for any HTML in the function, e.g
```JavaScript
const stillBreaks = ()=>{
let root = <h1>hellow world <h1/>;
return root;
}
```

**Comment by mordra** [comment]
If you can't try/catch the error, it's better to err on the safe side and miss some pure components as they will still be picked up by a full refresh.

**Comment by gadicc** [comment]
Yeah, you're right about both of those things.  It would be nice to match on any tags, but I can think of a few edge cases and don't want to get too complicated - unfortunately we can't try/catch so yeah would rather miss some pure components (although the hotload should still work because it will just bubble up to the component that includes it).
