### ISSUE TITLE
Missing class properties transform

### ISSUE THREAD

**Issue by sammkj** [gadicc/meteor-react-hotloader#16]
I tried to add `stage-0`. But I got the following error:

```
   While processing files with gadicc:ecmascript-hot (for target web.browser):
   client/test.js:5:2: /client/test.js: Missing class properties transform.
```
here's my `.babelrc` file:

```

  "presets": [
    "es2015",
    "stage-0",
    "react",
    "meteor"
  ],
  "env": {
    "development": {
      "plugins": [
        ["react-transform", {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }, {
            "transform": "react-transform-catch-errors",
            "imports": ["react", "redbox-react"]
          }]
        }]
      ]
    }
  }
}

```

If I add `transform-class-properties` to plugins, the error goes away. But I didn't need to do this for my other projects that are not using this package. Any guidance on how to properly fix would be appreciated!

**Comment by gadicc** [comment]
There are some ordering issues at play, because the `meteor` preset includes a number of the same plugins that some of those other presets do too.  For me I could fix this simply by putting `meteor` at the top of the preset list.

I'm probably going to stop forcing the `meteor` preset to be included in the future, just need to spend some time looking at exactly which plugins are included and if there is anything Meteor specific there too which could be included separately.

**Comment by sammkj** [comment]
Thank you @gadicc. I got it fixed now!
