### ISSUE TITLE
Readonly error

### ISSUE THREAD

**Issue by tomitrescak** [gadicc/meteor-react-hotloader#2]
I am not sure why is this happening, but when I remove underscores from the method names in create_comment.jsx, I receive following error:

```
While processing files with gadicc:ecmascript-hot (for target web.browser):
   client/modules/comments/components/create_comment.jsx: /client/modules/comments/components/create_comment.jsx: "create" is read-only (This is an error on an internal node.
   Probably an internal error. Location has been estimated.)
```

If I put them back on, all works.

Following works:

```javascript
_create() {
      const text = this.refs["text"]["value"];
      const { create, postId } = this.props;
      create(postId, text);
      this.refs["text"]["value"] = '';
}
```

Following does not

```javascript
create() {
      const text = this.refs["text"]["value"];
      const { create, postId } = this.props;
      create(postId, text);
      this.refs["text"]["value"] = '';
}
```

**Comment by gadicc** [comment]
Hey, @tomitrescak!  Nice to see you here :)

It's because of a [bug in babel](https://phabricator.babeljs.io/T6712), where you can't let/const a var with the same name as the containing function.  Looks like it's been fixed but not sure which release it will get into.

**Comment by gadicc** [comment]
Fixed in [babel 6.4.5](https://phabricator.babeljs.io/T6999#72277); meteor-babel is still on [6.2.4](https://github.com/meteor/babel/blob/master/package.json#L32) for now, though.

**Comment by tomitrescak** [comment]
@gadicc thanks, makes sense. And kudos, what a fantastic tool this is! It works as exactly as explained. I hoped that I can ditch Webpack workarounds, but I am one of those strange lunatics that likes typescript, and it is not yet possible to use typescript with meteor 1.3. Anyways, I Hope that this will make it into the core soon;) thanks!

**Comment by gadicc** [comment]
Thanks!  Still early days, but slowly addressing unsupported cases to get this somewhere nice.  Definitely let me know any differences you find from the webpack implementation!  There are some cases we'll never be able to handle, with the route we're taken, but some things are just lack of foresight and can be fixed.  We'll see if anyone else manages to bring typescript to meteor :)

This will never make it into core as is, but could serve as the basis for something official that can be planned better.

And also a big thanks to you too, because your wallaby.js contribution to mantra has just got me into this too, and this is definitely going to be a huge time saver.  *Time is everything!*
