### ISSUE TITLE
Packages should be debug only

### ISSUE THREAD

**Issue by timbotnik** [gadicc/meteor-react-hotloader#23]
Hi there,

We've had some reports of issues with this package on Galaxy.  It appears that the app server goes into an infinite CPU spin upon launch from a production bundle (when a .meteor folder does not exist):

https://github.com/gadicc/meteor-react-hotloader/blob/2f70731dc7128e2eb975d38b08a31bd080969cfb/babel-compiler-hot/babelrc.js#L28

I suggest you make these packages `debugOnly` as it seems they wouldn't be useful in production mode?

**Comment by gadicc** [comment]
**Firstly, this is fixed in the just-released `gadicc:ecmascript-hot@1.3.0_4`.**

Thanks for reporting this.

The package was originally intended as a `debugOnly` package (for the hotloading), but because of the `.babelrc` support, it's required in production too (for those that need this) - at least until Meteor officially offers this, and I hope this package can contribute to that.

Both these features require modifications to the core `babel-compiler`, so it's not easy to separate them.  So for now at least, the best I can do, is fix any issues as quickly as possible after they're reported.  (Also, a lot of the package code isn't loaded in production; this particular error was of course from the `.babelrc` code).

*Having said all that, this particular bug is an embarrassment and I sincerely apologize to all those it affected.*

I'd also like to thank you for taking the time to go through the package source and open this issue, that's great customer service from MDG!  I guess it wasn't the initial suspect either so I apologize also for the time involved in tracking this issue down.

**Comment by timbotnik** [comment]
Ok great, thanks for the quick fix!

**Comment by gadicc** [comment]
Sure.  Thanks again for bringing this to my attention.

**Comment by rickmed** [comment]
@gadicc I see in my production bundle some packages relates to this package, should they be? is there a fix currently?
