### ISSUE TITLE
Consider passing custom options.Module to makeInstaller?

### ISSUE THREAD

**Issue by benjamn** [gadicc/meteor-react-hotloader#3]
If you want to make `module.hot` available to all modules, you can provide your own `Module` constructor as an [option](https://github.com/gadicc/meteor-react-hotloader/blob/5262574aa42408142653c0b0862ecd790d9b3b86/modules-runtime/install-hot.js#L11) when you call `makeInstaller`.

If that doesn't make any sense, or doesn't work, let me know and I can provide more details.

**Comment by gadicc** [comment]
Hey, @benjamn, great seeing you here :)

The original aim for this project was a lot more modest - just react hot loading (using a partial and fake HMR implementation).  But in light of your [comments on the forum](https://forums.meteor.com/t/help-test-react-hotloading-in-native-meteor-i-e-no-webpack/17523/39?u=gadicc), I'm going to aspire for full HMR support, as per webpack's API, so that this can work with any module (e.g. redux's built-in hmr support).

I've made a start here and it indeed looks a lot cleaner.  The full API is a lot more involved though and my time is a bit limited atm.  I'll keep you posted.

Also FYI, relating to a previous issue you bought up, here's what hot loading looks like with native ES6 imports in webpack2: https://github.com/webpack/webpack/issues/1885.
