### ISSUE TITLE
=> Exited with code: 1 on releases > `1.3.1-fast.3`

### ISSUE THREAD

**Issue by clayne11** [gadicc/meteor-react-hotloader#30]
```
   While building for web.browser:
   packages/casalova:user-availability-view/user-availability-view.js:11:6: Unexpected token (11:6)
   packages/casalova:routes/components/open-paging-modal.js:8:30: Unexpected token (8:30)
```

No idea what's wrong. This builds fine under `1.3.1-fast.3` and there's nothing abnormal happening at the spots it's referencing.

**Comment by gadicc** [comment]
It's a false positive on the stateless transformation.  Can you paste the function?  Easiest way to deal with these now is to just break the matching regex, e.g.

```js
const notAcomponent = ()  => ( something );
const /* nomatch */ notAcomponent = ()  => ( something );
```
I must see if we can give a more descriptive warning for these cases.

**Comment by gadicc** [comment]
This is why we don't do .js by default :-)  will try clarify further in the README too.

**Comment by clayne11** [comment]
Yeah I figured that out after I made the issue.

The first one is this:

```
const noop = () => {};
```

This was easy to fix (either by adding a comment or changing to a `function() {}`).

The second one is a little trickier:

```
const OpenPagingModal = ({location, children}, {router}) => (
  <PagingModal
    onBack={() => appHistory.goBack()}
    onClose={() => (
      router.push({
        pathname: '/map-search',
        query: location.query,
        state: location.state,
      })
    )}
    isOpen={true}>
    {children}
  </PagingModal>
);
```

I tried replacing the two inner `() => {}` functions with `function() {}` but it still wouldn't build.

**Comment by clayne11** [comment]
I think it might be complaining about the context actually now that I think about it.

**Comment by clayne11** [comment]
I tried avoiding the specific file in question using `pathMatch` but my attempt didn't work. Any idea what's wrong with this RegEx?

```
  "ecmascript-hot": {
    "transformStateless": {
      "pathMatch": "(?!open-paging-modal)\\.jsx?$"
    }
  }
```

I'm trying to skip the `packages/casalova:routes/components/open-paging-modal.js` file.

**Comment by clayne11** [comment]
Looks like my RegEx was just wrong.

This should do it:

```
^(?:(?!.*open-paging-modal).*\.jsx?)$
```

**Comment by clayne11** [comment]
Now I'm getting `Exited with code: 1`.

**Comment by gadicc** [comment]
Yeah, it's the context parameter... I didn't try cover cases like this yet.  Will track in https://github.com/gadicc/meteor-react-hotloader/issues/31.

Glad you got the pathMatch working.  In case you want to switch back, it's actually the outer function call that you want to make sure doesn't match, i.e.

```
const /* break here */ OpenPagingModal = ({location, children}, {router}) => (
```

Can you paste the full error and stack trace for the `Exited with code: 1` ?  The only thing that comes to mind now is https://github.com/gadicc/meteor-react-hotloader/issues/26#issuecomment-207951389 - can you see if those steps find anything and solve the problem?

Besides for the pain you described in this issue, how are you enjoying the `fast` releases?

**Comment by gadicc** [comment]
Oh wow, there was also a very unfortunate [caching issue](https://github.com/gadicc/meteor-react-hotloader/issues/18#issuecomment-207953785) which means many of your changes in the code weren't seen anyway.  Sorry :(  I guess you spent a lot of time not understanding why things were having no affect, I apologize for that :(  Fixed in `gadicc:ecmascript-hot@1.3.1-fast.6`.

**Comment by clayne11** [comment]
The fun thing with `Exited with code: 1` is that you basically get no trace at all where it's happening. It's my least favorite part of Meteor.

```
[[[[[ ~/workspace/r3ntr_meteor ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Starting gadicc:ecmascript-hot server on port 3002.

W20160410-12:37:10.894(-4)? (STDERR) WARNING: npm peer requirements not installed:
W20160410-12:37:10.895(-4)? (STDERR)  - react@15.0.1 installed, react@0.14.x needed
W20160410-12:37:10.895(-4)? (STDERR)  - react-addons-pure-render-mixin@15.0.1 installed, react-addons-pure-render-mixin@0.14.x needed
W20160410-12:37:10.895(-4)? (STDERR)
W20160410-12:37:10.895(-4)? (STDERR) Read more about installing npm peer dependencies:
W20160410-12:37:10.895(-4)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160410-12:37:10.896(-4)? (STDERR)
I20160410-12:37:12.289(-4)? Kadira: Successfully connected
=> Exited with code: 1
```

**Comment by gadicc** [comment]
Yeah this is totally useless :(  Just wanted to double check that you checked out the steps in `https://github.com/gadicc/meteor-react-hotloader/issues/26#issuecomment-207951389`; i have an even better fix for this in the next version, but either way, the problem if it happened from an old version could stick around until manual kill or reboot.  I'd expect a different error in that case though, but it's the only thing I can really think of now.

I'm keeping this in mind while working through the code, looking out for anything that could cause an error like this.  Anywhere we manually exit is without an error code and with a console.log() explanation first.  I'm not sure why no error is being printed.  But the only major change since 1.3.1_1 is the "accelerator" code, which is what makes me think it's that earlier problem.

Anyway, please confirm you tried to find the runaway accelerator process or a reboot, and also what OS you're on, and I'll continue to keep an eye on this.

**Comment by clayne11** [comment]
Yeah I followed all of your debugging steps to no avail and I've also tried rebooting, and deleting `.meteor/local`. It simply exists with code 1.

I'm using an MBP 15" 2015 with OSX 10.11.4.

**Comment by gadicc** [comment]
Sorry, because I only have more debugging steps for you :)

1. Same thing when running on a different port?
1. Same thing in a fresh project?  i.e. meteor create and replace `ecmascript`
1. If it works in a fresh project, can you try `rm -rf .meteor/local/{b*,i*,p*,s*}` in your projDir?  That last part in curly braces is important, as it targets everything except for `db` which contains your database!  If anything isn't found there (some stuff from local packages) it's ok too.  This is my top guess for now.

If that still doesn't work, could you share your project?

I'm going out now but will get back to this later or tomorrow.

**Comment by clayne11** [comment]
1. Doesn't work.
2. Works fine on a fresh project.
3. I deleted my entire `.meteor/local` folder and that didn't help.

**Comment by clayne11** [comment]
I figured it out!

See this issue: https://github.com/meteor/meteor/issues/6812

It's Meteor related. Not sure the root cause yet but I have a workaround and my project is building. Thanks for the help.

**Comment by gadicc** [comment]
:(

Ok, so, I understand that:

1. This is a problem with the package, since your project works without it
1. This is specific to your project

Without seeing the code - which I totally understand that you can't share - I'm not sure how else I can help at this point :(  Especially with such an unhelpful error.

Can you try `gadicc:ecmascript-hot@=1.3.1-fast.10` from yesterday, in case any of my recent changes by chance fix the problem?

Otherwise will continue to leave this issue open in case anyone else experiences and will keep an eye out for anything that could cause a crash.

You could also try removing other packages and see if they make a difference, maybe something else is interacting badly with ecmascript-hot.

**Comment by clayne11** [comment]
I have tried `gadicc:ecmascript-hot@=1.3.1-fast.10` and it's still crashing unfortunately. I really wish Meteor would give us better error messages.

**Comment by clayne11** [comment]
I managed to get up and running.

I removed the `transformStateless` from my `package.json` and it builds fine so it's something related to stateless functional components. I should have tried that before.

Do you have any clues on how I could track down which stateless functional components might be causing the problem?

**Comment by clayne11** [comment]
My guess is that when the transform runs it's breaking a component which is causing `Exited with code: 1` because a some of the code is malformed when Meteor tries to build it.

**Comment by clayne11** [comment]
I figured it out. The current transform transforms all functions that look like this:

`const test = ({prop1, props2}) => {return <div/>})`

I propose that it should only transform variables that start with an uppercase letter:

`const Test = ({prop1, props2}) => {return <div/>})`

When I made this change my issue with stateless functional components went away. I'm going to submit a PR for this change because capitalized component names are the standard in React.

**Comment by gadicc** [comment]
Hey wow, these look like quite a few productive hours here :>  Really happy you figured this out, and even more so that it was followed up with a PR.

I've never seen a silent error from false positives before, it usually always throws an error and recently I even added code to show what the transformed code looks like around where the error occured.  I wonder what the ultimately transformed file looked like, and why this caused this error, but I guess I care more that it's solved now!
